wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.13.2
    cli_version: 0.16.6
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1740951385.0
    t:
      1:
      - 5
      - 53
      - 55
      - 105
      2:
      - 5
      - 53
      - 55
      - 105
      3:
      - 23
      4: 3.13.2
      5: 0.16.6
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
