wandb_version: 1

adapter_path:
  desc: null
  value: outputs/finetune/lora_adapter
device:
  desc: null
  value: null
batch_size:
  desc: null
  value: 1
domains_evaluated:
  desc: null
  value: []
temperature:
  desc: null
  value: 0.7
_wandb:
  desc: null
  value:
    python_version: 3.13.2
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.49.0
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1740727901.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      - 98
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 2
      - 13
      - 15
      - 16
      - 23
      4: 3.13.2
      5: 0.16.6
      6: 4.49.0
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
