wandb_version: 1

system:
  desc: null
  value:
    os: Darwin
    os_version: 15.3.1
    python_version: 3.13.2
    torch_version: 2.6.0
    device_type: mps
    cpu_count: 14
    memory_gb: 48.0
    chip_model: Apple M4 Pro
training_params:
  desc: null
  value: {}
model_params:
  desc: null
  value: {}
_wandb:
  desc: null
  value:
    python_version: 3.13.2
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.49.0
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1740705157.0
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 105
      3:
      - 2
      - 13
      - 15
      - 16
      - 23
      4: 3.13.2
      5: 0.16.6
      6: 4.49.0
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
